# Generated by Django 4.1.3 on 2022-12-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_birthdate_user_is_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_employee",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
